apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rag-search
  labels:
    app: rag-search
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rag-search
  template:
    metadata:
      labels:
        app: rag-search
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc-http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
